FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir streamlit requests

COPY frontend.py .

EXPOSE 777

CMD ["streamlit", "run", "frontend.py", "--server.port=777", "--server.address=0.0.0.0"]